//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeamCasing_ButtonCreate {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class BeamCast_Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BeamCast_Settings defaultInstance = ((BeamCast_Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BeamCast_Settings())));
        
        public static BeamCast_Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cD1_Ratio {
            get {
                return ((double)(this["cD1_Ratio"]));
            }
            set {
                this["cD1_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cP1_Ratio {
            get {
                return ((double)(this["cP1_Ratio"]));
            }
            set {
                this["cP1_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cP1_Min {
            get {
                return ((double)(this["cP1_Min"]));
            }
            set {
                this["cP1_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cMax1_Ratio {
            get {
                return ((double)(this["cMax1_Ratio"]));
            }
            set {
                this["cMax1_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cMax1_Max {
            get {
                return ((double)(this["cMax1_Max"]));
            }
            set {
                this["cMax1_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rD1_Ratio {
            get {
                return ((double)(this["rD1_Ratio"]));
            }
            set {
                this["rD1_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rP1_Ratio {
            get {
                return ((double)(this["rP1_Ratio"]));
            }
            set {
                this["rP1_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rP1_Min {
            get {
                return ((double)(this["rP1_Min"]));
            }
            set {
                this["rP1_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rMax1_RatioD {
            get {
                return ((double)(this["rMax1_RatioD"]));
            }
            set {
                this["rMax1_RatioD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rMax1_RatioW {
            get {
                return ((double)(this["rMax1_RatioW"]));
            }
            set {
                this["rMax1_RatioW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cD2_Ratio {
            get {
                return ((double)(this["cD2_Ratio"]));
            }
            set {
                this["cD2_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cP2_Ratio {
            get {
                return ((double)(this["cP2_Ratio"]));
            }
            set {
                this["cP2_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cP2_Min {
            get {
                return ((double)(this["cP2_Min"]));
            }
            set {
                this["cP2_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cMax2_Ratio {
            get {
                return ((double)(this["cMax2_Ratio"]));
            }
            set {
                this["cMax2_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cMax2_Max {
            get {
                return ((double)(this["cMax2_Max"]));
            }
            set {
                this["cMax2_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rD2_Ratio {
            get {
                return ((double)(this["rD2_Ratio"]));
            }
            set {
                this["rD2_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rP2_Min {
            get {
                return ((double)(this["rP2_Min"]));
            }
            set {
                this["rP2_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rMax2_RatioD {
            get {
                return ((double)(this["rMax2_RatioD"]));
            }
            set {
                this["rMax2_RatioD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rMax2_RatioW {
            get {
                return ((double)(this["rMax2_RatioW"]));
            }
            set {
                this["rMax2_RatioW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double rP2_Ratio {
            get {
                return ((double)(this["rP2_Ratio"]));
            }
            set {
                this["rP2_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkLink {
            get {
                return ((bool)(this["checkLink"]));
            }
            set {
                this["checkLink"] = value;
            }
        }
    }
}
