//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipeTagger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Test_text {
            get {
                return ((string)(this["Test_text"]));
            }
            set {
                this["Test_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("標稱+系統+BOP/COP")]
        public string PI_2nd_Selected {
            get {
                return ((string)(this["PI_2nd_Selected"]));
            }
            set {
                this["PI_2nd_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("標稱+系統+BOP/COP")]
        public string DT_C_2nd_Selected {
            get {
                return ((string)(this["DT_C_2nd_Selected"]));
            }
            set {
                this["DT_C_2nd_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WxH+系統+BOD")]
        public string DT_R_2nd_Selected {
            get {
                return ((string)(this["DT_R_2nd_Selected"]));
            }
            set {
                this["DT_R_2nd_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("材質+標稱+BOP")]
        public string CN_2nd_Selected {
            get {
                return ((string)(this["CN_2nd_Selected"]));
            }
            set {
                this["CN_2nd_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("服務類型+標稱+BOD")]
        public string CT_2nd_Selected {
            get {
                return ((string)(this["CT_2nd_Selected"]));
            }
            set {
                this["CT_2nd_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int label_dist_mm {
            get {
                return ((int)(this["label_dist_mm"]));
            }
            set {
                this["label_dist_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int label_length_mm {
            get {
                return ((int)(this["label_length_mm"]));
            }
            set {
                this["label_length_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L_圓形管標籤_標註符號")]
        public string PI_1st_Selected {
            get {
                return ((string)(this["PI_1st_Selected"]));
            }
            set {
                this["PI_1st_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L_圓形風管標籤_標註符號")]
        public string DT_C_1st_Selected {
            get {
                return ((string)(this["DT_C_1st_Selected"]));
            }
            set {
                this["DT_C_1st_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L_方形風管標籤_標註符號")]
        public string DT_R_1st_Selected {
            get {
                return ((string)(this["DT_R_1st_Selected"]));
            }
            set {
                this["DT_R_1st_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L_電管標籤_標註符號")]
        public string CN_1st_Selected {
            get {
                return ((string)(this["CN_1st_Selected"]));
            }
            set {
                this["CN_1st_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L_電纜架標籤_標註符號")]
        public string CT_1st_Selected {
            get {
                return ((string)(this["CT_1st_Selected"]));
            }
            set {
                this["CT_1st_Selected"] = value;
            }
        }
    }
}
